### PR TITLE
Fixed logo in Navbar

### PR DESCRIPTION
**Pull request by kcholew4**
Fixed logo in navbar ([issue#10](https://github.com/openwisp/openwisp-template-library-frontend/issues/10))

**Before:**
logo_before

**After:**
logo_after

### CODE REVIEW

**Comment by NoumbissiValere** [comment]
Excellent work @atevin187 . It looks great. I will test it locally ASAP and give you feedback. 
In the meantime, please can you move on to another tasks?

**Comment by rafiudd** [comment]
Nice work @atevin187

**Comment by rafiudd** [comment]
I am not a mentor for this task, but you can update your commit message to be more clean and for tracking bug in future.

Commit guidelines here: http://openwisp.io/docs/developer/contributing.html#how-to-commit-your-changes-properly

**Review by nemesifier — CHANGES_REQUESTED** [review]
@atevin187 commit message should be:

```
[header] Fix logo in Navbar

Closes #10 
```

Please read our [Commit Message Style Guidelines](http://openwisp.io/docs/developer/contributing.html#commit-message-style-guidelines).

**Review by nemesifier — APPROVED** [review]

**Pull request merged**
